---
- name: Destroy VM
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml
  environment:
    VMWARE_HOST: "{{ vcenter_hostname | default(lookup('ansible.builtin.env', 'VMWARE_HOST')) }}"
    VMWARE_USER: "{{ vcenter_username | default(lookup('ansible.builtin.env', 'VMWARE_USER')) }}"
    VMWARE_PASSWORD: "{{ vcenter_password | default(lookup('ansible.builtin.env', 'VMWARE_PASSWORD')) }}"
    VMWARE_VALIDATE_CERTS: "{{ vcenter_validate_certs | default(lookup('ansible.builtin.env', 'VMWARE_VALIDATE_CERTS')) }}"

  pre_tasks:
    - name: Check Inputs
      ansible.builtin.assert:
        that: vcenter_resource_prefix
        fail_msg: You must set the variable vcenter_resource_prefix to some string

  tasks:
    - name: Power Off VM
      community.vmware.vmware_guest:
        name: "{{ test_vm_name }}"
        folder: "{{ vcenter_folder }}"
        cluster: "{{ vcenter_cluster }}"
        datacenter: "{{ vcenter_datacenter }}"
        state: poweredoff
    - name: Destroy VM
      community.vmware.vmware_guest:
        name: "{{ test_vm_name }}"
        folder: "{{ vcenter_folder }}"
        cluster: "{{ vcenter_cluster }}"
        datacenter: "{{ vcenter_datacenter }}"
        state: absent
    # - name: Destroy Folder
    #   vmware.vmware.folder:
    #     datacenter: "{{ vcenter_datacenter }}"
    #     folder_type: vm
    #     relative_path: "{{ vcenter_folder }}"
    #     state: absent
